spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1065975634829-jkq80gv78ojclbfgs9pr0830cnjclt1d.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: http://ec2-43-201-59-98.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/google


#google login oauth 설정_ #1