spring:
  config:
    activate:
      on-profile: prod

#  datasource: #todo prod rds 설정
#    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/Mentoring?serverTimezone=UTC}
#    username: ${JDBC_DATABASE_USERNAME:root}
#    password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
#    hikari:
#      connection-timeout: 30000
#      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create #todo 배포 완료후 none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      username: sa
      password:
      data-locations: classpath*:db/data.sql
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1065975634829-jkq80gv78ojclbfgs9pr0830cnjclt1d.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: https://justicementoring.site/login/oauth2/code/google
server:
  port: 8080
logging:
  level:
    root: info
    org.hibernate.SQL: info
    pnu: info


