spring:

#
#  datasource:
#    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/Mentoring?serverTimezone=UTC}
#    username: ${JDBC_DATABASE_USERNAME:root}
#    password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
#    hikari:
#      connection-timeout: 30000
#      maximum-pool-size: 10
#

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB  # 파일 하나의 최대 크기
      max-request-size: 10MB  # 전체 요청의 최대 크기
file:
  upload-dir: \Users\\User\\workspace\\ch01\\mentoring\\uploads  # 서버에서 파일이 저장되는 기본 경로
  web-dir: /web/uploads  # 웹에서 접근 가능한 기본 경로
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
