#spring:
#  profiles:
# #   include: oauth
#    active: local
#  mvc:
#    format:
#      date: yyyy-MM-dd
#      date-time: yyyy-MM-dd'T'HH:mm:ss
#      time: HH:mm:ss
#
#error:
#  handling:
#    http-status-in-json-response: true
#    exception-logging: message_only #NO_LOGGING
#    full-stacktrace-http-statuses: 5xx
#    log-levels:
#      5xx: ERROR
#    servlet:
#      multipart:
#        maxFileSize: 10MB # 파일 하나의 최대 크기
#        maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
#thymeleaf:
#  cache: false
#  check-template-location: true
#  prefix: classpath:/templates
#  suffix: .html
#  enabled: true
#
#
#
#

spring:

  #
  #  datasource:
  #    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/Mentoring?serverTimezone=UTC}
  #    username: ${JDBC_DATABASE_USERNAME:root}
  #    password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
  #    hikari:
  #      connection-timeout: 30000
  #      maximum-pool-size: 10
  #


  #google login oauth profiles 설정_ #1
  profiles:
    include: oauth

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    servlet:
      multipart:
        maxFileSize: 10MB # 파일 하나의 최대 크기
        maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
thymeleaf:
  cache: false
  check-template-location: true
  prefix: classpath:/templates/
  suffix: .html
  enabled: true
