spring:
  profiles:
 #   include: oauth
    active: local
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
  ecurity:
    oauth2:
      client:
        registration:
          google:
            client-id: 1065975634829-jkq80gv78ojclbfgs9pr0830cnjclt1d.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google

error:
  handling:
    http-status-in-json-response: true
    exception-logging: message_only #NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    servlet:
      multipart:
        maxFileSize: 10MB # 파일 하나의 최대 크기
        maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
thymeleaf:
  cache: false
  check-template-location: true
  prefix: classpath:/templates
  suffix: .html
  enabled: true




