spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1065975634829-jkq80gv78ojclbfgs9pr0830cnjclt1d.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

#google login oauth 설정_ #1